{% set version = "1.3" %}

package:
  name: text-unidecode
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/text-unidecode/text-unidecode-{{ version }}.tar.gz
  sha256: bad6603bb14d279193107714b288be206cac565dfa49aa5b105294dd5c4aab93

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - text_unidecode

about:
  home: https://github.com/kmike/text-unidecode/
  license: Artistic
  license_family: OTHER
  license_file: LICENSE
  summary: "The most basic Text::Unidecode port"

extra:
  recipe-maintainers:
    - ocefpaf
